#!/usr/bin/env python
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path.cwd()
DISC = PROJECT_ROOT / "artifacts" / "discovery"
CONFIGS = PROJECT_ROOT / "configs"
RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

CONFIGS.mkdir(parents=True, exist_ok=True)
DISC.mkdir(parents=True, exist_ok=True)


def q(x: Any) -> str:
    if x is None:
        return "null"
    return '"' + str(x).replace('"', '\\"') + '"'


def has_col(cols: list[str], name: str) -> bool:
    return name in set(cols)


def choose_existing(cols: list[str], choices: list[str]) -> str | None:
    s = set(cols)
    for c in choices:
        if c in s:
            return c
    return None


def block(name: str, mapping: dict[str, str | None]) -> list[str]:
    out = [f"  {name}:"]
    for k, v in mapping.items():
        out.append(f"    {k}: {q(v)}")
    return out


def main() -> int:
    source = DISC / "3.0_schema_mapping.json"
    if not source.exists():
        raise FileNotFoundError(f"Missing {source}. Run 3.0 first.")

    obj = json.loads(source.read_text())
    schemas = obj.get("schemas", {})
    fisd_issue_cols = schemas.get("fisd_issue", {}).get("columns", [])
    bondret_cols = schemas.get("wrds_bondret", {}).get("columns", [])
    contrib_bond_cols = schemas.get("contrib_bond_returns", {}).get("columns", [])
    trace_cols = schemas.get("trace_enhanced_trades", {}).get("columns", [])
    link_cols = schemas.get("bond_firm_link", {}).get("columns", [])

    trace = dict(obj.get("columns", {}).get("trace", {}))

    fisd = dict(obj.get("columns", {}).get("fisd", {}))
    # Important corrections from the 3.0 auto-mapper:
    # 1. coupon_type is not a numeric coupon. Numeric coupon is available in wrdsapps_bondret;
    #    FISD coupon details require fisd_coupon_info, which we will profile later.
    # 2. FISD has a redeemable field that is the best conservative callable proxy for v1 screens.
    fisd["coupon"] = None
    fisd["coupon_type"] = choose_existing(fisd_issue_cols, ["coupon_type"])
    fisd["callable_flag"] = choose_existing(fisd_issue_cols, ["redeemable", "announced_call"])
    fisd["putable_flag"] = choose_existing(fisd_issue_cols, ["putable"])
    fisd["convertible_flag"] = choose_existing(fisd_issue_cols, ["convertible", "exchangeable"])
    fisd["asset_backed_flag"] = choose_existing(fisd_issue_cols, ["asset_backed"])
    fisd["perpetual_flag"] = choose_existing(fisd_issue_cols, ["perpetual"])
    fisd["defaulted_flag"] = choose_existing(fisd_issue_cols, ["defaulted"])

    returns = dict(obj.get("columns", {}).get("returns", {}))
    # Important correction: price_eom is the monthly return-panel price; offering_price is static issue pricing.
    returns["price"] = choose_existing(bondret_cols, ["price_eom", "price_ldm", "price_l5m", "offering_price"])
    returns["bond_return"] = choose_existing(bondret_cols, ["ret_eom", "ret_ldm", "ret_l5m"])
    returns["yield"] = choose_existing(bondret_cols, ["yield", "t_yld_pt"])
    returns["excess_return"] = None

    returns_fallback = {
        "cusip": choose_existing(contrib_bond_cols, ["cusip"]),
        "date": choose_existing(contrib_bond_cols, ["date"]),
        "bond_return": choose_existing(contrib_bond_cols, ["ret_eom"]),
        "excess_return": choose_existing(contrib_bond_cols, ["ret_exc", "ret_texc"]),
        "price": choose_existing(contrib_bond_cols, ["price_eom"]),
        "yield": choose_existing(contrib_bond_cols, ["yield"]),
        "duration": choose_existing(contrib_bond_cols, ["duration"]),
        "rating_num": choose_existing(contrib_bond_cols, ["rating_num"]),
        "amount_outstanding": choose_existing(contrib_bond_cols, ["amount_outstanding"]),
    }

    link = dict(obj.get("columns", {}).get("link", {}))
    # fang_link is issuer-CUSIP based, not bond-CUSIP based. Keep it optional.
    link["issuer_cusip"] = choose_existing(link_cols, ["issuer_cusip"])
    link["cusip"] = None

    yaml_lines = [
        "# Auto-generated by scripts/3.1_schema_patch.py",
        "# This patch corrects unsafe 3.0 auto-mapper choices before 4.x extraction.",
        "",
        "libraries:",
        '  trace_primary: "trace_enhanced"',
        '  trace_fallback: "trace_standard"',
        '  fisd_issue_master: "fisd_fisd"',
        '  fisd_common: "fisd_common"',
        '  bond_returns_primary: "wrdsapps_bondret"',
        '  bond_returns_fallback: "contrib_corporate_bond_returns"',
        '  bond_firm_link: "contrib_bond_firm_link"',
        "",
        "tables:",
        '  trace_trades: "trace_enhanced.trace_enhanced"',
        '  trace_fallback_trades: "trace_standard.trace"',
        '  trace_clean: "wrdsapps_bondret.trace_enhanced_clean"',
        '  fisd_issues: "fisd_fisd.fisd_issue"',
        '  fisd_issuer: "fisd_fisd.fisd_issuer"',
        '  fisd_common_issue_issuer: "fisd_common.issue_issuer"',
        '  fisd_coupon_info: "fisd_fisd.fisd_coupon_info"',
        '  fisd_amount_outstanding: "fisd_fisd.fisd_amount_outstanding"',
        '  bond_returns: "wrdsapps_bondret.bondret"',
        '  bond_returns_std: "wrdsapps_bondret.bondret_std"',
        '  bond_returns_fallback: "contrib_corporate_bond_returns.bonds"',
        '  bond_firm_link: "contrib_bond_firm_link.fang_link"',
        "",
        "columns:",
    ]
    yaml_lines += block("trace", trace)
    yaml_lines += block("fisd", fisd)
    yaml_lines += block("returns", returns)
    yaml_lines += block("returns_fallback", returns_fallback)
    yaml_lines += block("link", link)

    out_yaml = CONFIGS / "schema_map.yaml"
    out_yaml.write_text("\n".join(yaml_lines) + "\n", encoding="utf-8")

    patch_report = {
        "run_utc": datetime.now(timezone.utc).isoformat(),
        "input": str(source.relative_to(PROJECT_ROOT)),
        "output": str(out_yaml.relative_to(PROJECT_ROOT)),
        "patches": {
            "fisd.coupon": "set to null because 3.0 incorrectly mapped coupon_type as numeric coupon",
            "fisd.callable_flag": fisd.get("callable_flag"),
            "returns.price": returns.get("price"),
            "returns_fallback.excess_return": returns_fallback.get("excess_return"),
            "link.cusip": "set to null because fang_link is issuer-CUSIP based",
        },
        "columns": {
            "trace": trace,
            "fisd": fisd,
            "returns": returns,
            "returns_fallback": returns_fallback,
            "link": link,
        },
    }
    (DISC / "3.1_schema_patch_report.json").write_text(json.dumps(patch_report, indent=2), encoding="utf-8")

    md = [
        "# 3.1 Schema patch report",
        "",
        f"- Run UTC: `{patch_report['run_utc']}`",
        f"- Output config: `{patch_report['output']}`",
        "",
        "## Corrections applied",
        "",
        "| Field | Action |",
        "|---|---|",
        "| `fisd.coupon` | Set to `null`; `coupon_type` is categorical, not numeric coupon. |",
        f"| `fisd.callable_flag` | Set to `{fisd.get('callable_flag')}` as conservative callable proxy. |",
        f"| `returns.price` | Set to `{returns.get('price')}` instead of static `offering_price`. |",
        f"| `returns_fallback.excess_return` | Set to `{returns_fallback.get('excess_return')}`. |",
        "| `link.cusip` | Set to `null`; `fang_link` uses issuer CUSIP, not bond CUSIP. |",
        "",
        "## Next script",
        "",
        "Run `bash run_4.0.sh` to extract and screen FISD issue master.",
        "",
    ]
    (DISC / "3.1_schema_patch_report.md").write_text("\n".join(md), encoding="utf-8")

    print("[WROTE]", out_yaml)
    print("[WROTE]", DISC / "3.1_schema_patch_report.json")
    print("[WROTE]", DISC / "3.1_schema_patch_report.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
